### ISSUE TITLE
[poll] should this be a fork or standalone crate ?

### ISSUE THREAD

**Issue by robjtede** [robjtede/rustversion-msrv#2]
Please vote:

- ❤️ for standalone → only keep the `msrv` macro
- 👀 for fork of `rustversion` → port its updates to this crate

**Comment by timClicks** [comment]
Looking at the docs between this crate and the original, I was wondering whether you could add a specific "Use case" for `msrv`. That might make the situation clearer.

**Comment by robjtede** [comment]
Added to the readme:

The motivating use case for the `msrv` macro added by this crate is to ensure a stable compiler error output when running negative trybuild tests. Guarding your test function like this means you only need to update the .stderr files when you bump your MSRV, not (potentially) every stable release (or worse). Of course, try make sure that your CI is actually running an MSRV job in its set.

```rust
#[rustversion_msrv::msrv]
#[test]
fn trybuild() {
   // ...
}
```

**Comment by robjtede** [comment]
v0.100.0 released with only `msrv` macro
